### ISSUE TITLE
I am unclear on copyright permissions.

### ISSUE THREAD

**Issue by s4m-mo** [naturalis/Custom-databases-DNA-sequences#10]
I am unsure, it is a slight grey area for me, but would it be possible to use the match.tsv dataset (not all columns, just the family phylum, genus, order, class, species and nucleotide sequences) for a Python neural network module? I'd like to have some datasets that you can load automatically in my module. I will eventually publish it on PyPI and notify you if you'd like to see. Would this be possible without breaching the License?

**Comment by rvosa** [comment]
You certainly have our permission to use these data for that, and in fact I'm rather interested in what you are trying to do - could you say a bit more about that?

BTW so the MIT licensing basically means for us that we would like you to cite/reference our work where relevant, that's all.

**Comment by s4m-mo** [comment]
Well, it is presently unreleased, but I am in the process of refining my neural network module, that'll be written in raw Python so it can be run on other devices that support Python but not things like `tensorflow` and `keras`. An example is various amateur robotics products such as EV3 or other similar things.
I can later provide a link to it, I'll send it to you on here or somewhere on this page. I wanted to have some built-in datasets for usage without needing to process data yourself. I'll eventually make it available through `pip` so you can install it like any other external module. I'll be sure to cite you in many places so it is clear.

Thank you very much!

**Comment by rvosa** [comment]
Interesting! So, how will you use the nn on our data? To train some kind of classifier?

**Comment by s4m-mo** [comment]
It'd probably be for deducing the species from the nucleotide sequence. It is a great, comprehensive database you've got!

**Comment by s4m-mo** [comment]
@rvosa It is not finished yet, and the DNA data is not presently fully loaded in with a method in the Python module, but here is a link to the `easyNeuron` neural networks module. I may also start a few projects with this database. 

[Link is here.](https://github.com/Password-Classified/easyNeuron)

**Comment by s4m-mo** [comment]
Hi there, @rvosa,

Sorry 😬, about the module, which has not been developed 🛠 for in a while, but the development is picking itself back up at the moment, as I have made the decision to redesign 🎨 the whole thing. I'll be sure to add your database 📊 and credit it!

Many Thanks.
