### ISSUE TITLE
add a data folder

### ISSUE THREAD

**Issue by rvosa** [naturalis/Custom-databases-DNA-sequences#5]
to the root of the repo, add a folder called data that contains:

- the NSR exports: i) taxonomy, ii) synonyms
- BOLD exports, one for each genus
- FASTA files, match and mismatch

**Comment by bjanker** [comment]
Upload prevented for Megaselia datafile due to being over 100MB. 'Repository data quota' error while using Git Large File Storage (LFS). 

All other data is accounted for.

**Comment by rvosa** [comment]
It would be good if there was a README in the root of the data folder that explains what (types of) files are in this folder structure and why they are there. When are they produced during the running of the pipeline? What do they demonstrate? That sort of thing.

To reduce storage requirements, it would be good if the files could be archived in a single zip file.

**Comment by bjanker** [comment]
Readme added. Script adjusted to write/read obtained public sequence data as zip file.
